apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: payoffs.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: payoffs
    singular: payoff
    kind: PayOff
    shortNames:
    - pf