spring:
  application:
    name: stark-spark-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: stark-spark-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8082

kafka:
  topics:
    SendToSparkNormal: SendToSparkNormal
    SendToSparkVip: SendToSparkVip
    CallbackTopic: CallbackTopic
  consumer:
    group-id: stark-spark-group
  message:
    timeout: 30000
    poll-interval: 1000

spark:
  clusternum: 1 